# Generated by Django 4.2.4 on 2023-11-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=30)),
                ('fin_co_no', models.CharField(max_length=30)),
                ('fin_prdt_cd', models.CharField(max_length=30)),
                ('intr_rate_type', models.CharField(max_length=30)),
                ('intr_rate_type_nm', models.CharField(max_length=30)),
                ('save_trm', models.CharField(max_length=30, null=True)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=30)),
                ('fin_co_no', models.CharField(max_length=30)),
                ('kor_co_nm', models.CharField(max_length=30)),
                ('fin_prdt_cd', models.CharField(max_length=30)),
                ('fin_prdt_nm', models.CharField(max_length=30)),
                ('join_way', models.CharField(max_length=30)),
                ('mtrt_int', models.CharField(max_length=100)),
                ('spcl_cnd', models.CharField(max_length=100)),
                ('join_deny', models.CharField(max_length=30)),
                ('join_member', models.CharField(max_length=30)),
                ('etc_note', models.CharField(max_length=100)),
                ('max_limit', models.CharField(max_length=30, null=True)),
                ('dcls_strt_day', models.CharField(max_length=30)),
                ('dcls_end_day', models.CharField(max_length=30, null=True)),
                ('fin_co_subm_day', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SavingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=30)),
                ('fin_co_no', models.CharField(max_length=30)),
                ('fin_prdt_cd', models.CharField(max_length=30)),
                ('intr_rate_type', models.CharField(max_length=30)),
                ('intr_rate_type_nm', models.CharField(max_length=30)),
                ('rsrv_type', models.CharField(max_length=30, null=True)),
                ('rsrv_type_nm', models.CharField(max_length=30, null=True)),
                ('save_trm', models.CharField(max_length=30, null=True)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=30)),
                ('fin_co_no', models.CharField(max_length=30)),
                ('kor_co_nm', models.CharField(max_length=30)),
                ('fin_prdt_cd', models.CharField(max_length=30)),
                ('fin_prdt_nm', models.CharField(max_length=30)),
                ('join_way', models.CharField(max_length=30)),
                ('mtrt_int', models.CharField(max_length=100)),
                ('spcl_cnd', models.CharField(max_length=100)),
                ('join_deny', models.CharField(max_length=30)),
                ('join_member', models.CharField(max_length=30)),
                ('etc_note', models.CharField(max_length=100)),
                ('max_limit', models.CharField(max_length=30, null=True)),
                ('dcls_strt_day', models.CharField(max_length=30)),
                ('dcls_end_day', models.CharField(max_length=30, null=True)),
                ('fin_co_subm_day', models.CharField(max_length=30)),
            ],
        ),
    ]
