# Generated by Django 4.2.4 on 2023-11-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoption',
            name='dcls_month',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='depositoption',
            name='fin_co_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='depositoption',
            name='fin_prdt_cd',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='depositoption',
            name='intr_rate_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='depositoption',
            name='intr_rate_type_nm',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='dcls_month',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='dcls_strt_day',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='etc_note',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='fin_co_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='fin_co_subm_day',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='fin_prdt_cd',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='fin_prdt_nm',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='join_deny',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='join_member',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='join_way',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='kor_co_nm',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='mtrt_int',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='depositproduct',
            name='spcl_cnd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savingoption',
            name='dcls_month',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='savingoption',
            name='fin_co_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='savingoption',
            name='fin_prdt_cd',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='savingoption',
            name='intr_rate_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='savingoption',
            name='intr_rate_type_nm',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='dcls_month',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='dcls_strt_day',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='etc_note',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='fin_co_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='fin_co_subm_day',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='fin_prdt_cd',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='fin_prdt_nm',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='join_deny',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='join_member',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='join_way',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='kor_co_nm',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='mtrt_int',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savingproduct',
            name='spcl_cnd',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
